name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: pytorch/pytorch:2.1.0-cpu  # or latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python dependencies (CPU-only)
        run: |
          python -m pip install --upgrade pip
          pip install pybind11

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        run: |
          cd build
          cmake .. -Dpybind11_DIR=$(python3 -m pybind11 --cmakedir)
        shell: bash

      - name: Build project
        run: |
          cd build
          make -j$(nproc)
        shell: bash

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
        shell: bash
